### PR TITLE
Move our standard Uninstaller into Gravity Forms uninstall page

### LINKED ISSUE #1191: Move Gravity PDF Uninstaller to Settings -> Uninstall
**Description**
Gravity Forms has moved all their add-on uninstaller under Settings -> Uninstall. We should do the same

**Step To Reproduce**
1. Go to Settings -> Uninstall with a Gravity Forms add-on enabled

**Expected behavior**
Show Gravity PDF on this list

**Screenshots**
Screen Shot 2021-03-01 at 11 28 20 am

### PR DESCRIPTION
**Pull request by jakejackson1**
## Description

Gravity Forms has migrated all their add-on uninstaller to their Settings -> Uninstall page. This PR moves Gravity PDF's uninstaller to the same location.

Resolves #1191 

## Testing instructions
1. Go to Settings->Uninstall
2. Select Gravity PDF's Uninstall button
3. Confirm you want to proceed
4. Plugin is uninstalled and deactivated

## Screenshots 
Screen Shot 2021-03-12 at 11 12 44 am

## Checklist:
- [ ] I've tested the code.
- [X] My code is easy to read, follow, and understand
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation / docblocks.

### CODE REVIEW

**Comment by jakejackson1** [comment]
@debbieellis7 when you have time, could you please update the E2E uninstall test so it points to the Gravity Forms Uninstall settings page, where this option now resides?

Screen Shot 2021-03-12 at 11 12 44 am

File: src/Controller/Controller_Uninstaller.php [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+if ( ! defined( 'ABSPATH' ) ) {
+	exit;
+}
+
+/**
+ * Class Helper_Uninstaller
+ *
+ * @package GFPDF\Helper
+ */
+class Controller_Uninstaller extends Helper_Abstract_Controller {
```
Comment (jakejackson1) [inline src/Controller/Controller_Uninstaller.php:31]: This file needs appropriate Docblocks
